import random
import string


def passwordgen(diff=""):
    result = ""
    if diff in ["w", "weak"]:       # MULTIPLE INPUT OPTIONS NEED TO BE COVERED
        result = random.choice(["poopyhead123", "sleepyface1990", "ihavenoidea"])
    else:
        symbols = "*-+_!?.:"
        chars = string.ascii_letters + string.digits
        for i in range(4):          # 4 FIRST CHARACTER ARE LETTERS OR NUMBERS
            result += random.choice(chars)
        for i in range(17):
            result += random.choice(chars+symbols)
    return result


def main():
    while True:
        request = input("Request new password? (Y/N)")
        if request.casefold() == "y":
            diff = input("Strenght of password? (weak/strong)")
            print(passwordgen(diff.lower()))
            if diff.lower() not in ["w", "weak", "s", "strong"]:
                print("Strong password has been generated by default. For a weaker password please type \"weak\"!")
        else:
            break
    return


if __name__ == '__main__':
    main()
