import random
import string


def passwordgen(diff=""):
    result = ""
    chars = string.ascii_letters
    digits = string.digits
    if diff in ["w", "weak"]:       # MULTIPLE INPUT OPTIONS NEED TO BE COVERED
        result = random.choice(["poopyhead123", "sleepyface1990", "ihavenoidea"])
    elif diff in ["m", "medium"]:
        while len(result) < 4:
            result = random.choice(open("/usr/share/dict/words").read().splitlines())
        result += ''.join(random.choice(chars+digits) for _ in range(4))
    else:
        symbols = "[!@#$%^&*()?]"
        result += random.choice(digits)
        result += random.choice(symbols)
        result += ''.join(random.choice(chars+symbols) for _ in range(8))
    return result


def main():
    while True:
        request = input("Request new password? (Y/N)")
        if request.casefold() == "y":
            diff = input("Strenght of password? (weak/medium/strong)")
            print(passwordgen(diff.lower()))
            if diff.lower() not in ["w", "weak", "s", "strong", "m", "medium"]:
                print("Strong password has been generated by default. For a weaker password please type \"weak\" or \"medium\"!")
        else:
            break
    return


if __name__ == '__main__':
    main()
